---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 & DynamoDB based remote backend for Terraform'
# Parameters:
#   BucketName:
#     Description: Name of the S3 bucket for storing terraform states
#     Type: String
#     AllowedPattern: "^([a-z]|(\\d(?!\\d{0,2}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})))([a-z\\d]|(\\.(?!(\\.|-)))|(-(?!\\.))){1,61}[a-z\\d\\.]$"
#     ConstraintDescription: Can only contain lowercase characters, numbers, periods,
#       and dashes
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Join
        - "-"
        - - "terraform-s3-backend"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"  #Random Suffix for bucket name
      BucketEncryption:
            ServerSideEncryptionConfiguration: 
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256      
      LifecycleConfiguration:
        Rules:
          - Id: IntelligentRule
            Status: Enabled
            Transitions:
              - TransitionInDays: 1
                StorageClass: INTELLIGENT_TIERING
      VersioningConfiguration:
        Status: Enabled
  
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: terraform-state-lock
      BillingMode: PAY_PER_REQUEST
      ContributorInsightsSpecification:
          Enabled: false
      AttributeDefinitions:
          - AttributeName: LockID
            AttributeType: S
      KeySchema: 
          - AttributeName: LockID
            KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 0
          WriteCapacityUnits: 0


  
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content