AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role that can be assumed by another IAM role in an external account
Parameters:
  RoleName:
    Type: String
    Default: "iam_assumable_role_created_by_cloudformation"
    Description: Name of the role to be created
  ExternalRoleArn:
   Type: String
   Default: "arn:aws:iam::REPLACE_WITH_EXTERNAL_AWS_ACCOUNT_NUMBER:role/role_name_in_external_account"
   Description: ARN of the external role from another account that is allowed to assume this role in this account.

Resources:
  IAMRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - Ref: ExternalRoleArn
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      RoleName: !Ref RoleName
      Policies:
        - PolicyName: inline_policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Sid: AllowReadingMetricsFromCloudWatch
              Effect: Allow
              Action:
              - cloudwatch:DescribeAlarmsForMetric
              - cloudwatch:DescribeAlarmHistory
              - cloudwatch:DescribeAlarms
              - cloudwatch:ListMetrics
              - cloudwatch:GetMetricData
              - cloudwatch:GetInsightRuleReport
              Resource: "*"
            - Sid: AllowReadingLogsFromCloudWatch
              Effect: Allow
              Action:
              - logs:DescribeLogGroups
              - logs:GetLogGroupFields
              - logs:StartQuery
              - logs:StopQuery
              - logs:GetQueryResults
              - logs:GetLogEvents
              Resource: "*"
            - Sid: AllowReadingTagsInstancesRegionsFromEC2
              Effect: Allow
              Action:
              - ec2:DescribeTags
              - ec2:DescribeInstances
              - ec2:DescribeRegions
              Resource: "*"
            - Sid: AllowReadingResourcesForTags
              Effect: Allow
              Action: tag:GetResources
              Resource: "*" 
