#cloud-config
apt_upgrade: true

packages:
  - apache2
  - httpd
  - docker

write_files:
  - owner: root:root
    path: /var/www/html/index.html
    permissions: "0644"
    content: |
      <h1>Hei, NEP!</h1>
      <h2>Good Morning :) </h2>

runcmd:
  - |
    #!/bin/bash
    echo "Welcome to webserver"
    sudo systemctl enable docker.service
    sudo systemctl start docker.servi
    sudo usermod -a -G docker ec2-user
